export const colors = {
  primary: '#C8102E', // Deep Blood Red from logo
  primaryDark: '#9A0B22',
  primaryLight: '#FDDDE1',
  primarySoft: '#FEF0F2',
  surfaceSoft: '#F8FAFC',
  navyDark: '#0F172A',
  text: '#0F172A',
  textSecondary: '#475569',
  textMuted: '#94A3B8',
  border: '#E2E8F0',
  borderLight: '#F1F5F9',
  success: '#10B981',
  successLight: '#ECFDF5',
  warning: '#F59E0B',
  warningLight: '#FFFBEB',
  danger: '#C8102E',
  dangerLight: '#FEF0F2',
  teal: '#0D9488',
  tealLight: '#CCFBF1',
  orange: '#EA580C',
  orangeLight: '#FFEDD5',
  surface: '#FFFFFF',
  background: '#F8FAFC',
  card: '#FFFFFF',
};
